# Generated by Django 2.2 on 2021-05-18 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
