# Generated by Django 2.2 on 2021-05-18 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20210518_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 18, 18, 43, 22, 21899)),
        ),
    ]
