# Generated by Django 2.2 on 2021-05-20 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20210518_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ManyToManyField(null=True, related_name='expense_cat', to='expenses.Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateField(default=datetime.date(2021, 5, 19)),
        ),
    ]
