# Generated by Django 2.2 on 2021-06-02 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20210519_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateField(default=datetime.date(2021, 6, 2)),
        ),
    ]
