# Generated by Django 3.2.5 on 2021-07-07 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20210602_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='spend_date',
            field=models.DateField(default=datetime.date(2021, 7, 7)),
        ),
    ]
