# Generated by Django 3.2.5 on 2021-07-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=255, null=True),
        ),
    ]
